apiVersion: v1
kind: Pod
metadata:
  name: event-bus-pod
  labels:
    app: node
    rel: alpine
spec:
  containers:
    - name: event-buscontainer
      image: event-busimage
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 4005
