apiVersion: v1
kind: Pod
metadata:
  name: moderation-pod
  labels:
    app: node
    rel: alpine
spec:
  containers:
    - name: moderationimage
      image: moderationimage
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 4003
