apiVersion: v1
kind: Pod
metadata:
  name: posts-pod
  labels:
    app: node
    rel: alpine
spec:
  containers:
    - name: posts-container
      image: postsimage
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 4000
