apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus-depl
spec:
  selector:
    matchLabels:
      app: app-event-bus
  template:
    metadata:
      labels:
        app: app-event-bus
    spec:
      containers:
        - name: event-bus
          image: event-bus-image
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: event-bus-service
spec:
  selector:
    app: app-event-bus
  ports:
    - name: event-bus
      protocol: TCP
      port: 4005
      targetPort: 4005
