apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderation-depl
spec:
  selector:
    matchLabels:
      app: app-moderation
  template:
    metadata:
      labels:
        app: app-moderation
    spec:
      containers:
        - name: moderation
          image: moderation-image
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: moderation-service
spec:
  selector:
    app: app-moderation
  ports:
    - name: moderation
      protocol: TCP
      port: 4003
      targetPort: 4003
